sonar.projectKey=ourcookiestuff_Object-Design
sonar.organization=ourcookiestuff

sonar.modules=zad3,zad4,zad5

zad3.sonar.projectName=zad3-kotlin
zad3.sonar.sources=zad3/src/main/kotlin
zad3.sonar.java.binaries=zad3/target/classes

zad4.sonar.projectName=zad4-go
zad4.sonar.sources=zad4

zad5.sonar.projectName=zad5-js
zad5.sonar.sources=zad5/client/src
zad5.sonar.exclusions=**/*.test.ts,**/*.spec.ts,node_modules/**