sonar.projectKey=ourcookiestuff_Object-Design
sonar.organization=ourcookiestuff

sonar.modules=zad3,zad4,zad5

zad3.sonar.projectName=zad3-kotlin
zad3.sonar.projectBaseDir=zad3
zad3.sonar.sources=src/main/kotlin
zad3.sonar.java.binaries=target/classes

zad4.sonar.projectName=zad4-go
zad4.sonar.projectBaseDir=zad4
zad4.sonar.sources=.

zad5.sonar.projectName=zad5-js
zad5.sonar.projectBaseDir=zad5/client
zad5.sonar.sources=src
zad5.sonar.exclusions=**/*.test.ts,**/*.spec.ts,node_modules/**