name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: zad5/client

      - name: Run ESLint
        run: npx eslint src
        working-directory: zad5/client

  lint-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ktlint
        uses: nicowillis/ktlint-action@v1.0.1
        with:
          path: zad3

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: zad4